    modSpikes = types.core.ProcessingModule(...
             'description','AP processing',...
             'dynamictable', []  ...
                   );
               
    modSubStats = types.core.ProcessingModule(...
         'description', 'subthreshold parameters',...
         'dynamictable', []  ...
               );
           
    modAPP = types.core.ProcessingModule(...
                         'description', 'Tables with processed spike pattern data',...
                         'dynamictable', []  ...
                               );    
    modNoiseP = types.core.ProcessingModule(...
                         'description', 'Tables with processed noise stimulus spike pattern data',...
                         'dynamictable', []  ...
                               );   
                           
    modQC = types.core.ProcessingModule(...
                         'description', 'Table with QC parameter',...
                         'dynamictable', []  ...
                               );     