function ICsummary = initICSummary(cellList)

temp = {cellList.name};
temp = cellfun(@(S) S(1:end-4), temp, 'Uniform', 0);
features = {...
    'Vrest' 'RinHD' 'RinSS' 'tau' 'Rheo' 'sagVrest' ...
    'sag' 'sagRat' 'sagAmp' 'widTP_LP' 'peakLP' 'thresLP' ...
    'fTrghLP' 'sTrghLP' 'peakUpStrkLP' 'peakDwStrkLP' ...
    'peakStrkRatLP' 'htTP_LP' 'lat' ...
    'CurrentStepSP' 'thresholdSP' 'fastTroughSP' 'slowTroughSP' 'heightTP_SP' ...
    'peakUpStrokeSP' 'peakDownStrokeSP' 'peakStrokeRatioSP' ...
    'latencySP' 'widthTP_SP' 'peakSP' 'rheoRt' 'lastQuisc'...
    'medInstaRt' 'DFR_P90' 'DFR_P10' 'DFR_IQR' 'AdaptRatB1B2' ...
    'AdaptRatB1B13' 'StimAdapB123' 'StimAdapB7_13' 'fIslope'...
    'maxRt' 'rectI' 'cvISI' 'HeroRt' 'HeroAmp' 'heroLat' ...
    'peakAdapt' 'adaptIdx' 'burst' 'TrghDiff' 'TrghRatio'...
    'Temperature' 'RinOffset'};

ICsummary = array2table(NaN(length(cellList),length(features)), ...
    'VariableNames', features,'RowNames', temp);

ICsummary.dendriticType(:) = {'NA'};
ICsummary.SomaLayerLoc(:) = {'NA'};
ICsummary.ReporterTag(:) = {'None'}; 
ICsummary.brainOrigin(:) = {'NA'};
ICsummary.Weight(:) = {'NA'};
ICsummary.Sex(:) = {'NA'};
ICsummary.Age(:) = {'NA'};
ICsummary.Species(:) = {'NA'};
end