    module_spikes = types.core.ProcessingModule(...
             'description','AP processing',...
             'dynamictable', []  ...
                   );
               
    module_subStats = types.core.ProcessingModule(...
         'description', 'subthreshold parameters',...
         'dynamictable', []  ...
               );
           
    module_APP = types.core.ProcessingModule(...
                         'description', 'Tables with processed spike pattern data',...
                         'dynamictable', []  ...
                               );    
                           
    module_QC = types.core.ProcessingModule(...
                         'description', 'Table with QC parameter',...
                         'dynamictable', []  ...
                               );     