%% Summary analysis output

writetable(ICsummary,['ephys_features_', date,'.csv'], 'WriteRowNames',true)

%% QC parameter for each cell
cells = fieldnames(QCparameterTotal);

for c = 1:length(cells)
    writetable(QCparameterTotal.(cell2mat(cells(c))), ...
                  [outDest,cell2mat(cells(c)),'_QC_parameter_',date,'.csv']);  
    writetable(QCpassTotal.(cell2mat(cells(c))), ...
                       [outDest,cell2mat(cells(c)),'_QC_pass_',date,'.csv']);  
end

%% QC logic sweeps per class matrix 

writetable(QC_removalsPerTag, [outDest,'QC_sweeps_per_tag_matrix_',date,'.csv'], 'WriteRowNames',true);  

%% procedure doc file
rowNames = {'Standard';'Cell-wise: initial R_a';'Cell-wise: initial R_a fract'; ...
    'Cell-wise: electrode drift'; 'Sweep-wise: bridge balance abs'; ...
    'Sweep-wise: bridge balance fract'; 'Sweep-wise: max I hold'; ...
    'Sweep-wise: maximum RMP'; ...
    'Sweep-wise: maximum deviation from start RMP'
    'Sweep-wise: pre post voltage stability'
    'Sweep-wise: st RMSE'; 'Sweep-wise: lt RMSE'; ...
    'Sweep-wise: LP averaging window pre stim'; ...
    'Sweep-wise: SP averaging window pre stim'; ...
    'Sweep-wise: start window post from stim onset LP'; ...  
    'Sweep-wise: start window post from stim onset stim SP'; ...
    'Sweep-wise: min Frac good Sp'; ...
    'Spike-wise: min SpAmp narrow'; 'Spike-wise: min SpAmp broad'; ...
    'Spike-wise: max threshold'; 'time'; 'path'; 'computer'; 'Matlab'   
    };
T= array2table([["Current Run", "Allen White Paper"];...
    [params.cutoffInitRa, 20];...
    [params.factorRelaRa, "0.2(human);0.15(mouse)"]; ...
    ["not implemented", "1 mV for every 10 min after start WC"]; ...
    [string(params.bridge_balance) , "20"]; ...
    [params.factorRelaRa , "0.2(human);0.15(mouse)"]; ...
    ["100 (abs)", "100 (abs)"]; ...
    [params.maximumRestingPot , "not implemented"]; ...
    [params.BwSweepMax, "not implemented"]; ...
    [params.maxDiffBwBeginEnd, "1"]; ...
    [params.RMSEst, "0.07"]; ...
    [params.RMSElt, "0.5"]; ...
    [params.LPqc_samplWind , "-"]; ...
    [params.SPqc_samplWind , "-"]; ...
    [params.LPqc_recovTime + 1000, "-"]; ...
    [params.SPqc_recovTime + 3, "-"]; ...
    [params.minGoodSpFra, "not implemented"]; ...
    [params.minDiffThreshold2PeakN, "not implemented"]; ...
    [params.minDiffThreshold2PeakB, "not implemented"]; ...
    [params.maxThreshold , "not implemented"]; ...    
    [string(datestr(now,'HH:MM:SS')), "-"]; ... 
    [mainFolder , "-"]; ... 
    [computer, "-"]; ... 
    [version, "-"]]...
     , 'RowNames', rowNames...
  );

writetable(T, [outDest,'procedure_doc_', date,'.csv'],'WriteRowNames',true, ...
    'WriteVariableNames', false);   