%% Summary analysis output

% parameters to include
varNames = {'new ID',...%'old ID',
    'temperature', ...
    'resistance', 'access resistance' , 'time constant', 'I amp sag', ...
    'sag absolute Vm', 'sag' , 'steadystate', 'sag ratio', 'rheobase',...
    'AP peak', 'AP threshold', 'AP half width (TP)', 'AP height (TP)', ...
    'peak up stroke','peak down stroke', 'peak stroke ratio', 'AP through', ...
    'AP fast through', 'AP slow through', 'max firing rate'};

T = table( ...%IC.ID_new,
    IC.ID, ... 
    IC.temperature,IC.resistance_ss,IC.access_resistance,...
    IC.time_constant,IC.subamp,IC.submin,IC.sag,...
    IC.steadystate,IC.sag_ratio,IC.rheobaseLP,...
    IC.peakLP,IC.thresholdLP,...
    IC.half_width_threshold_peak,...
    IC.height_threshold_peak,...
    IC.peak_up_stroke,IC.peak_down_stroke,IC.peak_stroke_ratio,IC.trough,...
    IC.fastTrough,IC.slowTrough,IC.maxFiringRate, 'VariableNames',varNames);
    writetable(T,[save_path,'ephys_features_', date,'.csv'], 'WriteRowNames',true)
    
T = table(IC.ID_new,IC.ID,IC.input_current_s,IC.firing_rate_s,IC.delay,IC.burst,...
    IC.latency,IC.cv_ISI,IC.adaptation1,IC.adaptation2,...
    IC.peak_adaptation1,IC.peak_adaptation2);
    writetable(T,[save_path,'firing_pattern_', date,'.csv'],...
        'WriteRowNames',true)
    
T = table(IC.ID,IC.wf);
    writetable(T,[save_path,'waveforms_', date,'.csv'],'WriteRowNames',true)