function Hd = lowPassFilt
%LOWPASSFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 29-Aug-2022 15:36:47

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 50000;  % Sampling Frequency

Fpass = 7500;        % Passband Frequency
Fstop = 8500;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 60;           % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
