
clear; tic

mainFolder = 'D:\output_ressource\QC\';            % main folder (EDIT HERE)
outDest = 'D:\output_ressource\website\';          % general path
cellList = dir([mainFolder,'*.nwb']);          


for n = 1:length(cellList)                                             % for all cells in directory
  cellFile = nwbRead([mainFolder,cellList(n).name]);
    for m = 1:unique(cellFile.general_intracellular_ephys_sweep_table.sweep_nr)
       cellFile.general_intracellular_ephys_sweep_table.sweep_nr.data.load(...
           find(cellFile.general_intracellular_ephys_sweep_table.sweep_nr.data.load==m))   %
        
        
    end
    
end


Data_compressed=types.untyped.DataPipe( ...
                  'data', data(:,1,s),...
                  'compressionLevel', 3,...
                  'chunkSize', [1000 1],...
                  'axis', 1);
              
             stimData_compressed=types.untyped.DataPipe( ...
                                   'data', stimData,...
                                   'compressionLevel', 3,...
                                   'chunkSize', [1000 1],...
                                   'axis', 1);
		     Data_compressed=types.untyped.DataPipe( ...
                  'data', data,...
                  'compressionLevel', 3,...
                  'chunkSize', [1000 1],...
                  'axis', 1);