function cellFile  = addColumns2SwTabl(cellFile,qc_tags)

cellFile.general_intracellular_ephys_intracellular_recordings.categories = ... 
[cellFile.general_intracellular_ephys_intracellular_recordings.categories' ...
    {'quality_control_pass'}];

cellFile.general_intracellular_ephys_intracellular_recordings.id = types.hdmf_common.ElementIdentifiers( ...
 'data', int64([0:cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims-1]));

cellFile.general_intracellular_ephys_intracellular_recordings.dynamictable.set( ...
  'quality_control_pass', types.hdmf_common.DynamicTable( ...
    'description', 'Parameters of quality control', ...
    'colnames', [qc_tags(2:length(qc_tags))] , ...
    'id', types.hdmf_common.ElementIdentifiers( ...
        'data', int64([0:...
        cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims-1]) ...
    ), ...
    'QC_total_pass', types.hdmf_common.VectorData( 'data', ...
          nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
        'Binary for total QC evaluation of sweep; pass = 1, fail=0' ... 
     ), ...
    'stRMSE_pre', types.hdmf_common.VectorData( 'data', ...
         nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
        'Binary for short-term root mean sqaure evaluation of prestimulus interval; pass = 1, fail=0' ...
     ), ...
    'stRMSE_post', types.hdmf_common.VectorData( 'data', ...
        nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
        'Binary for short-term root mean sqaure evaluation of poststimulus interval; pass = 1, fail=0' ...
     ), ...
    'ltRMSE_pre', types.hdmf_common.VectorData( 'data',  ...
         nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for long-term root mean sqaure evaluation of prestimulus interval; pass = 1, fail=0'...
      ), ...   
     'ltRMSE_post', types.hdmf_common.VectorData(  'data', ...
        nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for long-term root mean sqaure evaluation of poststimulus interval; pass = 1, fail=0'...
      ), ...   
     'diffVrest', types.hdmf_common.VectorData(  'data', ...
         nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of voltage difference between pre and post stimulus intervall; pass = 1, fail=0'...
     ), ...   
     'Vrest', types.hdmf_common.VectorData( 'data', ...
         nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of prestimulus membrane potential; pass = 1, fail=0'...
      ), ...   
      'holdingI', types.hdmf_common.VectorData( 'data',  ...
        nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of holding current value; pass = 1, fail=0'...
      ), ...   
      'betweenSweep', types.hdmf_common.VectorData(  'data', ...
         nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of across sweep variability (i.e. drift) of the prestimulus membrane potential; pass = 1, fail=0'...
      ), ...   
      'bridge_balance_abs', types.hdmf_common.VectorData(  'data', ...
        nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of absolute bridge balance value; pass = 1, fail=0'...
      ), ...     
     'bridge_balance_rela', types.hdmf_common.VectorData( 'data', ...
        nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
     'Binary for QC evaluation of relative bridge balance value; pass = 1, fail=0'...
      ), ...   
     'bad_spikes', types.hdmf_common.VectorData( 'data',  ...
       nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
        1)' , 'description', ...
<<<<<<< Updated upstream
     'Binary for QC evaluation of sweeps with bad spike wave forms; pass = 1, fail=0'),...
     'dummy', types.hdmf_common.VectorData( 'data',  ...
       nan(cellFile.general_intracellular_ephys_intracellular_recordings.id.data.dims, ...
=======
     'Binary for QC evaluation of sweeps with bad spike wave forms; pass = 1, fail=0'),...    
     'manuTP', types.hdmf_common.VectorData( 'data',  ...
       nan(cellFile.general_intracellular_ephys_intracellular_recordings.responses.id.data.dims, ...
>>>>>>> Stashed changes
        1)' , 'description', ...
     'Binary for QC evaluation of sweeps with bad spike wave forms; pass = 1, fail=0'...
  ) ...
 ) ...
);
     
end