function module_APP = fillNoiseMod(module_APP, SpPattrn)
    SpPattrn.ISIs = cellfun(@single,SpPattrn.ISIs,'UniformOutput',false);
   [ISIs_data_vector, ISIs_data_index] = util.create_indexed_column(SpPattrn.ISIs, 'path');
   SpPattrn.SpTimes = cellfun(@single,SpPattrn.SpTimes,'UniformOutput',false);
      
   ISI_table = types.hdmf_common.DynamicTable(...
                    'colnames', 'ISIs',...
                    'description', ...
                    'Table with all inter spike intervalls per sweep',...
                    'id', types.hdmf_common.ElementIdentifiers('data', ...
                                           0:length(ISIs_data_vector.data)) ,...
                    'ISIs', types.hdmf_common.VectorData(...
                                            'data', ISIs_data_vector.data,...
                                            'description', 'Interspike Intervals'...
                                        ),...
                    'ISIs_index', types.hdmf_common.VectorIndex(...
                                            'data', ISIs_data_index.data,...
                                            'target', types.untyped.ObjectView(...
                                              '/processing/Noise Stimulus/ISIs/')));                                       
   module_APP.dynamictable.set('ISIs', ISI_table);  
end