function [nwb, CS]  = importSweeps(nwb, CS, ic_elec_link)
             
CS.SwpAmp(CS.swpCt,1) =  single(round(h5read( ...
CS.filename, [CS.sweepPath, '/aibs_stimulus_amplitude_pa'])));

stimData = h5read(CS.filename, [CS.stimPath, '/data']);

if H5L.exists(H5G.open(H5F.open(CS.filename), CS.sweepPath),'bias_current','H5P_DEFAULT')
   CS.biasCurrent = h5read(CS.filename, [CS.sweepPath, '/bias_current']);
else
   CS.biasCurrent = single(0);
end

if H5L.exists(H5G.open(H5F.open(CS.filename), CS.sweepPath),...
        'capacitance_compensation','H5P_DEFAULT')
   CS.CapaComp = single(h5read(CS.filename, ...
                   [CS.sweepPath, '/capacitance_compensation']));
else
   CS.CapaComp = single(0);
end

if CS.SwpAmp(CS.swpCt,1)  < 0
  [~,temp] = findpeaks(-stimData); 
    if length(temp) < 2
      CS.StimOn(CS.swpCt,1) = int32(temp-1) ;
    else
      CS.StimOn(CS.swpCt,1) = int32(temp(2)-1);
    end
  CS.StimOff(CS.swpCt,1) = int32(find(stimData~=0, 1,'last'));
else
    [~,temp] = findpeaks(stimData); 
    if length(temp) < 2
       CS.StimOn(CS.swpCt,1) = int32(temp-1) ;
    else
       CS.StimOn(CS.swpCt,1) = int32(temp(2)-1);
    end
    CS.StimOff(CS.swpCt,1) = int32(find(stimData~=0, 1,'last')); 
end

nwb.acquisition.set( CS.sweepName, types.core.CurrentClampSeries( ...
    'bias_current', CS.biasCurrent, ... % Unit: Amp
    'bridge_balance', h5read(...
    CS.filename, [CS.sweepPath, '/bridge_balance']), ... % Unit: Ohm
    'capacitance_compensation', single(CS.CapaComp), ... % Unit: Farad
    'data', ...   
types.untyped.DataPipe('data', h5read(CS.filename, [CS.sweepPath, '/data']),...
'chunkSize', [1000 1],...
'axis', 1), ...
    'data_unit', h5readatt(...
             CS.filename, [CS.sweepPath, '/data'], 'unit'), ...
    'electrode', ic_elec_link, ...
    'stimulus_description', CS.stimName,...
    'sweep_number', CS.swpCt-1,... 
    'starting_time', h5read(...
        CS.filename, [CS.stimPath, '/starting_time']),...
    'starting_time_rate', h5readatt(...
        CS.filename, [CS.sweepPath, '/starting_time'], 'rate') ...
 ));

nwb.stimulus_presentation.set(CS.sweepName,...
types.core.CurrentClampStimulusSeries(...
    'electrode', ic_elec_link, ...
    'gain', NaN, ...
    'stimulus_description', CS.stimName,...
    'data_unit', h5readatt(...
             CS.filename, [CS.stimPath, '/data'], 'unit'), ...
    'data', types.untyped.DataPipe('data', stimData,'chunkSize', [1000 1],...
         'axis', 1), ...
    'sweep_number', CS.swpCt-1,...                     
    'starting_time', h5read(...
        CS.filename, [CS.stimPath, '/starting_time']),...
    'starting_time_rate', h5readatt(...
        CS.filename, [CS.stimPath, '/starting_time'], 'rate')...
  ));
    
end